### ISSUE TITLE
QQ7.1 表示报错

### ISSUE THREAD

**Issue by manyhelp** [fourbrother/icodetools#5]
第四步==> 转化jar文件为dex文件(可能需要消耗点时间) 开始处理classes.jar compile cmd:javac -encoding UTF-8 -cp libs\android.jar JWUtils.java UNEXPECTED TOP-LEVEL EXCEPTION: java.lang.RuntimeException: Exception parsing classes at com.android.dx.command.dexer.Main.processClass(Main.java:752) at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718) at com.android.dx.command.dexer.Main.access$1200(Main.java:85) at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes( Main.java:1645) at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpen er.java:284) at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.j ava:166) at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java :144) at com.android.dx.command.dexer.Main.processOne(Main.java:672) at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574) at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311) at com.android.dx.command.dexer.Main.run(Main.java:277) at com.android.dx.command.dexer.Main.main(Main.java:245) at com.android.dx.command.Main.main(Main.java:106) at cn.wjdiankong.jw.DoWorkUtils.jar2Dex(DoWorkUtils.java:147) at cn.wjdiankong.jw.JWMain.main(JWMain.java:89) Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebab e) or version (0034.0000) at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java: 472) at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:4 06) at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary (DirectClassFile.java:388) at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.jav a:251) at com.android.dx.command.dexer.Main.parseClass(Main.java:764) at com.android.dx.command.dexer.Main.access$1500(Main.java:85) at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684 ) at com.android.dx.command.dexer.Main.processClass(Main.java:749) ... 14 more 1 error; aborting H:\软件\安卓工具\icodetools-master>adb install -r signed.apk can't find 'signed.apk' to install H:\软件\安卓工具\icodetools-master>pause.. 请按任意键继续. . .

**Comment by deoplljj1** [comment]
之前也遇到了类似的问题，最后是自己用dx工具将jar还原回dex文件的。
